### ISSUE TITLE
Status bar overlapping

### ISSUE THREAD

**Issue by happiehappie** [IdleHandsApps/IHKeyboardAvoiding#39]
I have the following screen, blue background being the container view and my avoiding view.

![simulator screen shot - iphone se - 2017-09-21 at 00 40 28](https://user-images.githubusercontent.com/6497131/30656117-8c539d22-9e65-11e7-8f2d-682f8a9cb676.png)
However, when I present my keyboard, the container view overlaps with my status bar.
![simulator screen shot - iphone se - 2017-09-21 at 00 40 30](https://user-images.githubusercontent.com/6497131/30656158-ae8fa3c2-9e65-11e7-962e-2c7c4e0fd073.png)
Was wondering if there's any way to dodge this?
My self.view.clipsToBounds is already set to true if that matters

**Comment by fraserscottmorrison** [comment]
Im guessing you don't want the black view to go off the top of the screen?

Id put another UIView inside the blue view, then add the textfield and button to this new UIView. The new UIView can be your avoiding view.

**Comment by happiehappie** [comment]
But then won't the "another UIView" overlap with the black view?

**Comment by happiehappie** [comment]
Or is this the expected behavior?

**Comment by fraserscottmorrison** [comment]
Depends what you want. I'd add a constraints between the black view and the new view so that they can't overlap (e.g. min constraint height = 8) 

But depending on the size of the device you might not be able to fit everything on the screen. You might need to lower the priority of a constraint (e.g. black view top or height constraint) so that it'll move off the top or shrink if needed

**Comment by fraserscottmorrison** [comment]
Got it sorted?
